apiVersion: v1
kind: Pod
metadata:
  name: hrms-mysql
  labels:
    app: hrms-mysql
spec:
  containers:
    - name: mysql
      image: careerdeveloper1/hrms-mysql:v2
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: hrms_db
        - name: MYSQL_USER
          value: hrms_user
        - name: MYSQL_PASSWORD
          value: hrms_password
