apiVersion: v1
kind: Service
metadata:
  name: hrms-frontend
spec:
  selector:
    app: hrms-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort   # so you can access frontend in browser
