apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name: azurefile-storage
provisioner: file.csi.azure.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters: 
  secretName: azure-secret
  secretNamespace: default
  resourceGroup: webapp
  skuName: Standard_LRS



---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: azurefile-pvc
  labels: 
    app: azurefile
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce 
  resources: 
    requests:
      storage: 80Mi
  storageClassName: azurefile-storage

---

apiVersion: v1
kind: Pod
metadata: 
  name: vishalng
  namespace: default  
  labels:
    ac1: voltas1
spec: 
  nodeSelector:
    name1: vishal1
  containers:
    - name: vishal-ng
      image: nginx
      imagePullPolicy: IfNotPresent
      ports: 
        - containerPort: 80
      volumeMounts: 
      - mountPath: /usr/share/nginx/html
        name: vishal-vol
  
  volumes:
  - name: vishal-vol
    persistentVolumeClaim:
      claimName: azurefile-pvc

