apiVersion: v1
kind: Pod
metadata:
  name: hrms-backend
  labels:
    app: hrms-backend
spec:
  containers:
    - name: backend
      image: careerdeveloper1/hrms-backend:v2
      ports:
        - containerPort: 5000
      env:
        - name: DB_HOST
          value: hrms-mysql    # must match mysql service name later
        - name: DB_USER
          value: hrms_user
        - name: DB_PASSWORD
          value: hrms_password
        - name: DB_NAME
          value: hrms_db
        - name: DB_PORT
          value: "3306"
---
apiVersion: v1
kind: Service
metadata:
  name: hrms-backend
spec:
  selector:
    app: hrms-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

---

apiVersion: v1
kind: Pod
metadata:
  name: hrms-frontend
  labels:
    app: hrms-frontend
spec:
  containers:
    - name: frontend
      image: careerdeveloper1/hrms-frontend:v2
      ports:
        - containerPort: 80
      env:
        - name: VITE_API_URL
          value: http://hrms-backend:5000/api
---

apiVersion: v1
kind: Service
metadata:
  name: hrms-frontend
spec:
  selector:
    app: hrms-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort   # so you can access frontend in browser

---
apiVersion: v1
kind: Pod
metadata:
  name: hrms-mysql
  labels:
    app: hrms-mysql
spec:
  containers:
    - name: mysql
      image: careerdeveloper1/hrms-mysql:v2
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: hrms_db
        - name: MYSQL_USER
          value: hrms_user
        - name: MYSQL_PASSWORD
          value: hrms_password


---

apiVersion: v1
kind: Service
metadata:
  name: hrms-mysql
spec:
  selector:
    app: hrms-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
          
  
          
      
