apiVersion: v1
kind: Pod
metadata:
  name: hrms-backend
  labels:
    app: hrms-backend
spec:
  containers:
    - name: backend
      image: careerdeveloper1/hrms-backend:v2
      ports:
        - containerPort: 5000
      env:
        - name: DB_HOST
          value: hrms-mysql    # must match mysql service name later
        - name: DB_USER
          value: hrms_user
        - name: DB_PASSWORD
          value: hrms_password
        - name: DB_NAME
          value: hrms_db
        - name: DB_PORT
          value: "3306"
