apiVersion: v1
kind: Service
metadata: 
  name: ci-svc
  namespace: default
  labels:
    service1: vishal1
spec: 
  selector: 
    pm: modiji
  ports: 
  - port: 8082
    targetPort: 80
    protocol: TCP
    name: ci-svc-port-name
  type: ClusterIP


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vishal-dep
  namespace: default
  labels:
    app1: dep1

spec:
  replicas: 2
  selector:
    matchLabels:
      pm: modiji
  template:
    metadata:
      name: vishal1
      namespace: default
      labels: 
        pm: modiji
    spec:
      containers: 
      - name: vmm-cont
        image: careerdeveloper1/vishalmm:v4
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
  strategy: 
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate

