apiVersion: v1
kind: Pod
metadata:
  name: vishalng1
  namespace: default
  labels: 
    ac1: nginx1
spec:
  containers: 
  - image: nginx:alpine
    imagePullPolicy: IfNotPresent
    name: nginx-cont
    ports: 
    - containerPort: 80
      protocol: TCP
      name: nginxport
    volumeMounts: 
    - mountPath: /usr/share/nginx/html
      name: vishal-vol

  nodeName: vishal-worker
  os: 
    name: linux
  
  volumes: 
  - name: vishal-vol
    hostPath: 
      path: /mnt



