apiVersion: v1
kind: PersistentVolume
metadata: 
  name: local-pv
  namespace: default
  labels: 
    app1: pv1
spec: 
  accessModes: 
  - ReadWriteMany
  capacity: 
    storage: 100Mi
  local: 
    path: /mnt
  nodeAffinity: 
    required: 
      nodeSelectorTerms: 
      - matchExpressions: 
        - key: name1
          operator: In
          values:
          - vishal1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage


---



apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: local-pvc
  namespace: default
  labels: 
    app1: pvc1
spec:
  accessModes: 
  - ReadWriteMany
  resources: 
    requests: 
      storage: 90Mi
  storageClassName: local-storage

---

apiVersion: v1
kind: Pod
metadata:
  name: vishalng1
  namespace: default
  labels: 
    ac1: nginx1
spec:
  volumes: 
  - name: vishal-vol
    persistentVolumeClaim: 
      claimName: local-pvc
  containers: 
  - image: nginx:alpine
    imagePullPolicy: IfNotPresent
    name: nginx-cont
    ports: 
    - containerPort: 80
      protocol: TCP
      name: nginxport
    volumeMounts: 
    - mountPath: /usr/share/nginx/html
      name: vishal-vol
  os: 
    name: linux






