
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: azure-pv
  namespace: default
  labels: 
    app1: pv1
spec: 
  accessModes: 
  - ReadWriteMany
  capacity: 
    storage: 100Mi

  persistentVolumeReclaimPolicy: Retain
  storageClassName: azure-storage
  csi: 
    driver: file.csi.azure.com
    volumeHandle: vishal-volhand
    volumeAttributes: 
      shareName: vishalfc
    nodeStageSecretRef:
      name: azure-secret
      namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: azure-pvc
  namespace: default
  labels: 
    app1: pvc1
spec:
  accessModes: 
  - ReadWriteMany
  resources: 
    requests: 
      storage: 90Mi
  storageClassName: azure-storage
  ---
  apiVersion: v1
kind: Pod
metadata:
  name: vishalng1
  namespace: default
  labels: 
    ac1: nginx1
spec:
  containers: 
  - image: nginx:alpine
    imagePullPolicy: IfNotPresent
    name: nginx-cont
    ports: 
    - containerPort: 80
      protocol: TCP
      name: nginxport
    volumeMounts: 
    - mountPath: /usr/share/nginx/html
      name: vishal-vol
  os: 
    name: linux
  volumes: 
  - name: vishal-vol
    persistentVolumeClaim: 
      claimName: azure-pvc





# Note:- 
# 1. I am creating PV on azure file (cloud) azure file-- storage account--
#  file share-- storage account name:- vishalstore1, file share- vishalfc
# 2. as azure is a third party application for volume -- I have to create
#  a secret in my cluster for azure file share so that my cluster can 
# access the azure file share volume.
# 3. azure reference-- google search azurefile secret for kubernetes

# kubectl create secret generic azure-secret 
# --from-literal=azurestorageaccountname=vishalstore1
#  --from-literal=azurestorageaccountkey=
# 9ta/XDHXBDpQdRtpS1Ae3Mf9raNhJd0Mf8lgC0qpUsscstPI8tFYPlTDimwuPhlh49TJBFQRTYYN+ASt9J+1OQ==
