name: 1_vishalRunner_cr_rg_terra_vishal

on:
  workflow_dispatch:  # allows manual trigger from Actions tab

env:
  RESOURCE_GROUP: webapp_rg
  AZURE_REGION: ukwest
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS_VISHAL }}

jobs: 
  vishalRunner_cr_rg_terra_vishal: 
    runs-on: vishal

    steps: 
      # Check if az cli is installed, install only if missing
      - name: Ensure Azure CLI is installed
        run: |
          if command -v az >/dev/null 2>&1; then
            echo "✅ Azure CLI already installed"
            az version
          else
            echo "⚡ Installing Azure CLI..."
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          fi

      - name: Az login
        uses: azure/login@v2
        with: 
            creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

